### ISSUE TITLE
ASPDM URI Protocol & Package Sources

### ISSUE THREAD

**Issue by fincs** [ahkscript/ASPDM#10]
The current URI format should include the host name from which the package is to be downloaded (this is mandatory for it to be a correctly formed URI). IMO it should read like this: `aspdm://domain.name/packageid`

This also brings up another issue: I think it should be possible to add other additional package repositories in the ASPDM Client. It could be done in a similar way to what Eclipse does (look at the 'Work with' DDL):
![aaa](http://nexj-scheme.org/images/ecore/eclipse_install_new_sw.png)

**Comment by joedf** [comment]
Update to this...

**Examples:**
- `aspdm://aspdm.1eko.com/midi/user` will now prompt to install `midi.ahkp` from `aspdm.1eko.com` into the `User` Library.
- `aspdm://aspdm.ahkscript.org/samples/global` prompts to install `samples.ahkp` from `aspdm.ahkscript.org`  into the `Global` (StdLib) Library.
