### ISSUE TITLE
Running Package_Builder without Res folder leaves stub process

### ISSUE THREAD

**Issue by evilC** [ahkscript/ASPDM#15]
You get a "No icon" warning, but whatever, the script does not exit and no tray icon, so you need to kill via task manager.

Probably pretty edge-case, but worth a mention.

Also, Package_Builder seems to be quite happy when compiled, but same issue. Can you not `FileInstall` the Res files to make it portable?

**Comment by joedf** [comment]
Hmm, it was not meant to be run in compiled form, but thanks for reporting this.
Fixed, the process will no longer hang. FileInstall done.
**Commit:** https://github.com/ahkscript/ASPDM/commit/ce655fe02df4f6c9e00881b8ed3ef8c5cd1929b8
**Commit:** https://github.com/ahkscript/ASPDM/commit/20a252c990c05694af2c6ec37ed4e3d3a68c8684
