### ISSUE TITLE
ASPDM API is not responding

### ISSUE THREAD

**Issue by hoppfrosch** [ahkscript/ASPDM#21]
Don't know where to report else ....

Just installed ASPDM from http://aspdm.ahkscript.org/client/. 
Starting the client results in error: 
`The ASPDM API is not responding. The server might be down. Please try again in a while (5 min).`

Same happens when using the client-script directly from a fresh git-clone.....

BTW: Whats the current state of ASPDM?

**Comment by joedf** [comment]
Hmm... 
What do you get if you try loading this page directly? 
http://aspdm.ahkscript.org/api-php/status.php?_c=test123

**Comment by hoppfrosch** [comment]
Using the given URL in Browser, I get the following json-response
`{api:{"name":"aspdm","check":"test123"}}`

The exe and script still get the "server down" message....

**Comment by joedf** [comment]
Ok, I'll check it out real quick if I have time tonight.
To answer your other question, ASPDM is in a Beta/Mature state. It is mainly the website that needs work.

**Comment by joedf** [comment]
Ahkk ok, i got it. it's because `aspdm.2fh.co` and `ahk.cu.cc` are down.
`Show_AllPackSources` is now set to `false` by default.

**Comment by hoppfrosch** [comment]
Thanks for the fast fix

**Comment by hoppfrosch** [comment]
Thanks for the fast fix

**Comment by hoppfrosch** [comment]
Ooops ... too early: still doesn't work here ...

**Comment by joedf** [comment]
Go to settings and make sure to show only packs from one source only. ?

**Comment by hoppfrosch** [comment]
That's it! Thx ....

Is there a preferred source currently?

**Comment by joedf** [comment]
aspdm.ahkscript.org

Packages and account need to be added.
