### ISSUE TITLE
Always offline?

### ISSUE THREAD

**Issue by fjxhkj** [ahkscript/ASPDM#22]
I can't connect ASPDM server to download, it's always offline...

**Comment by joedf** [comment]
What is the "package source" setting that you have? Is it set to `aspdm.ahkscript.org`?
If so, can you verify if you can connect to `aspdm.ahkscript.org` in your webbrowser?

**Comment by joedf** [comment]
Looks like the installer was outdated. Please re-download the latest one.
Note: You might have to manually delete the `%AppData%\aspdm` folder.
http://aspdm.ahkscript.org/client/
```
MD5: b642cd72ca34f94cc4318c3f62ca41e0
SHA-1: fddd4bf2b86e19479c1d81a95f6e95a82685500e
```
